development:
  adapter: postgresql
  encoding: unicode
  database: rough_development
  pool: 5
  username: ndonias
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rough_test
  pool: 5
  username: ndonias
  password: